CREATE TABLE Movies(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    release_date int CHECK (release_date > 0),
    country text,
    duration int CHECK (release_date > 0)
);

INSERT INTO Movies(name, release_date, country, duration) VALUES ('Leon', 1994, 'France', 110);
INSERT INTO Movies(name, release_date, country, duration) VALUES ('Dancer in the Dark', 2000, 'France', 140);
INSERT INTO Movies(name, release_date, country, duration) VALUES ('Billy Elliot', 2000, 'France', 110);
INSERT INTO Movies(name, release_date, country, duration) VALUES ('The Godfather', 1972, 'USA', 175);
INSERT INTO Movies(name, release_date, country, duration) VALUES ('Forrest Gump', 1994, 'USA', 152);
INSERT INTO Movies(name, release_date, country, duration) VALUES ('The Prestige', 2006, 'USA', 130);
INSERT INTO Movies(name, release_date, country, duration) VALUES ('Knockin'' on Heaven''s Door', 1997, 'Germany', 87);
INSERT INTO Movies(name, release_date, country, duration) VALUES ('K-PAX', 2001, 'Germany', 120);
INSERT INTO Movies(name, release_date, country, duration) VALUES ('Inglourious Basterds', 2009, 'Germany', 153);
INSERT INTO Movies(name, release_date, country, duration) VALUES ('Harry Potter and the Sorcerer''s Stone', 2001, 'UK', 152);
INSERT INTO Movies(name, release_date, country, duration) VALUES ('Snatch', 2000, 'UK', 104);
INSERT INTO Movies(name, release_date, country, duration) VALUES ('Tenet', 2020, 'UK', 150);